# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the TypeScript source
RUN npm run build

# Expose port if needed (not strictly needed for stdio services)

# Run the MCP server
CMD [ "node", "./build/index.js" ]
